/*******************************************************************************
 * Copyright (c) 2013 University of Bergamo - Italy
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *   Paolo Vavassori - initial API and implementation
 *   Angelo Gargantini - utils and architecture
 ******************************************************************************/
/*
* generated by Xtext
*/
package citlab.model.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import citlab.model.citL.Aseed;
import citlab.model.citL.Constant;
import citlab.model.citL.Element;
import citlab.model.citL.Enumerative;
import citlab.model.citL.EnumerativeType;
import citlab.model.citL.CitModel;
import citlab.model.citL.Range;
import citlab.model.citL.Rule;
import citlab.model.citL.Seed;
import citlab.model.citL.Boolean;
import citlab.model.citL.Numbers;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class CitLLabelProvider extends DefaultEObjectLabelProvider {

	
		
		/**
		 * Image.
		 *
		 * @param citModel the model
		 * @return the string
		 */
		String image(CitModel citModel)

		{

			return "Model.png";
		}
		
		/**
		 * Image.
		 *
		 * @param citModel the model
		 * @return the string
		 */
		String image(Constant constant)

		{

			return "Constant.png";
		}
		/**
		 * Image.
		 *
		 * @param rule the rule
		 * @return the string
		 */
		String image(Rule rule)

		{

			return "Rule.png";
		}
		
		/**
		 * Image.
		 *
		 * @param aseed the aseed
		 * @return the string
		 */
		String image(Aseed aseed)

		{

			return "Aseed.png";
		}

		/**
		 * Image.
		 *
		 * @param ele the ele
		 * @return the string
		 */
		String image(Element ele)

		{

			return "Element.png";
		}
		
		/**
		 * Image.
		 *
		 * @param range the range
		 * @return the string
		 */
		String image(Range range)

		{

			return "Range.png";
		} 
		
		/**
		 * Image.
		 *
		 * @param numb the numb
		 * @return the string
		 */
		String image(Numbers numb)

		{

			return "Number.png";
		}
		
		/**
		 * Image.
		 *
		 * @param bool the bool
		 * @return the string
		 */
		String image(Boolean bool)

		{

			return "Boolean.png";
		}
		

		/**
		 * Image.
		 *
		 * @param enumerative the enumerative
		 * @return the string
		 */
		String image(Enumerative enumerative)

		{

			return "Enumerative.png";
		}
		
		/**
		 * Image.
		 *
		 * @param enumerativeT the enumerative t
		 * @return the string
		 */
		String image(EnumerativeType enumerativeT)

		{

			return "Type.png";
		}
		
		/**
		 * Image.
		 *
		 * @param seed the seed
		 * @return the string
		 */
		String image(Seed seed)

		{

			return "Seed.png";
		}

		/*
		 * //Labels and icons can be computed like this:
		 * 
		 * String text(MyModel ele) { return "my "+ele.getName(); }
		 * 
		 * String image(MyModel ele) { return "MyModel.gif"; }
		 */
	}
