/*
 * generated by Xtext
 */
package citlab.model.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import citlab.model.ui.internal.CitLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CitLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CitLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CitLActivator.getInstance().getInjector(CitLActivator.CITLAB_MODEL_CITL);
	}
	
}
