/*
* generated by Xtext
*/
package citlab.model;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CitLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return citlab.model.ui.internal.CitLActivator.getInstance().getInjector("citlab.model.CitL");
	}
	
}
